name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit Tests (Java 21)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run unit tests
        run: mvn -B -ntp -DskipITs test

      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: backend/**/target/surefire-reports/**
          if-no-files-found: ignore

  integration:
    name: Integration Tests (with services)
    runs-on: ubuntu-latest
    needs: unit
    defaults:
      run:
        shell: bash
        working-directory: backend

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: jobportal
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U postgres -d jobportal"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20
      redis:
        image: redis:7-alpine
        ports: [ "6379:6379" ]
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    env:
      SPRING_PROFILES_ACTIVE: test
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: jobportal

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run integration tests (Failsafe)
        run: mvn -B -ntp -DskipTests -DskipITs=false verify

      - name: Upload failsafe & jacoco reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-reports
          path: |
            backend/**/target/failsafe-reports/**
            backend/**/target/site/jacoco/**
          if-no-files-found: ignore

      - name: Dump service logs on failure
        if: failure()
        run: |
          echo "=== Docker logs: postgres ==="
          docker logs ${{ job.services.postgres.id }} || true
          echo "=== Docker logs: redis ==="
          docker logs ${{ job.services.redis.id }} || true
